### ISSUE TITLE
跑不起来啊

### ISSUE THREAD

**Issue by xiaoweiQ** [angleneo/educate-restting#1]
![image](https://user-images.githubusercontent.com/26682207/57506951-e4281500-732f-11e9-9cda-e326e8c8f4e6.png)

**Comment by xiaoweiQ** [comment]
已解决，要装axios和vue-cookie

**Comment by angleneo** [comment]
兄弟你在逗我， 这是要连数据库才能访问的，主要是我保存一下ts和vue2的使用语法。可以参考但是不建议vue2版本在生产中使用ts，等vue3出来吧
